title: KSV-LiLi
email: your-email@example.com
description: So radikal wie die Wirklichkeit.
baseurl: ""
url: "https://ksv-lili.at" # the base hostname & protocol for your site, e.g. http://example.com
domain: "ksv-lili.at"
twitter_username: ksv_lili

sass:
  implementation: sassc
  style: compact
  sass_dir: sass
  line_comments: false
  sourcemap: always

defaults:
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "news.html"
    values:
      sitemap: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
